version: "3.8"


services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest

    ports:
      - "8000:8000"

    environment:
      - DATABASE_URL=${DATABASE_URL}

    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

      restart_policy:
        condition: on-failure

      mode: replicated

      placement:
        constraints:
          - node.role == worker

      update_config:
        parallelism: 1